---
title: "FEM11152 - Individual Assignment Week 3: Case B"
author: "Kemal Ozbek - 692000"
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
header-includes:
   - "\\usepackage{fancyhdr}"
   - "\\usepackage{titling}"
   - "\\setlength{\\droptitle}{-1cm}"
   - "\\pretitle{\\begin{center}\\large\\vspace{-1cm}}"
   - "\\posttitle{\\end{center}}"
   - "\\preauthor{\\begin{center}\\large}"
   - "\\postauthor{\\end{center}\\vspace{-1.5cm}}"
   - "\\pagestyle{fancy}"
   - "\\fancyhead{}"
   - "\\fancyhead[R]{2023-11-16}"
   - "\\renewcommand{\\headrulewidth}{0pt}"
   - "\\renewcommand{\\footrulewidth}{0pt}"
   - "\\renewcommand{\\refname}{\\normalsize References}"
bibliography: references.bib
reference-section-title: References
---

```{r eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Library check
library(ltm)
library(vcd)
library(dplyr)
library(ggplot2)
library(corrplot)
library(caretEnsemble)
library(ggcorrplot)
library(tidyverse)
library(e1071)
library(cluster)
library(mclust)
library(caret)
library(naivebayes)
library(patchwork)
library(pROC)
```

```{r eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
# Data pre-processing 
load("JobChanges.RData")
dim(data)
head(data)
str(data)
summary(data)
```

```{r eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
## Data manipulation
categorize_experience <- function(experience) {
  if (experience <= 2) {
    return("Junior")
  } else if (experience <= 5) {
    return("Mid-level")
  } else if (experience <= 10) {
    return("Senior")
  } else if (experience <= 20) {
    return("Manager")
  } else {
    return("Executive")
  }
}
data$experience <- factor(sapply(data$experience, categorize_experience), 
                                   levels = c("Junior", "Mid-level", "Senior",
                                              "Manager", "Executive"))

rebin_company_size <- function(size) {
  if (size %in% c("<10", "10-49")) {
    return("0-49")
  } else if (size %in% c("50-99")) {
    return("50-99")
  } else if (size %in% c("100-500")) {
    return("100-500")
  } else if (size %in% c("500-999", "1000-4999")) {
    return("500-9999")
  } else {
    return("10000+")
  }
}
data$company_size <- factor(sapply(data$company_size, rebin_company_size),
                            levels = c("0-49", "50-99", "100-500", 
                                       "500-9999", "10000+"))

# Checking the distribution for each categorical variable
contingency_table_gender <- table(data$gender)
contingency_table_relevant_experience <- table(data$relevant_experience)
contingency_table_education_level <- table(data$education_level)
contingency_table_major_discipline <- table(data$major_discipline)
contingency_table_company_type <- table(data$company_type)

# Cramér's V & Chi-Squared Test
cramers_v <- function(x, y) {
  table <- table(x, y)
  chi_sq <- chisq.test(table)
  n <- sum(table)
  phi_sq <- chi_sq$statistic / n
  r <- nrow(table) - 1
  k <- ncol(table) - 1
  min <- min(r, k)
  v <- sqrt(phi_sq / (min * (n - 1)))
  p_value <- chi_sq$p.value
  return(c("Cramer's V" = v, "p-value" = p_value))
}
variable_combinations <- combn(names(data)[sapply(data, is.factor)], 2)

cramers_results <- apply(variable_combinations, 2, function(vars) {
  cat_vars <- lapply(vars, function(var_name) data[[var_name]])
  cramer_v_and_p_value <- do.call(cramers_v, cat_vars)
  return(cramer_v_and_p_value)
})
cramers_results_df <- as.data.frame(t(cramers_results))
colnames(cramers_results_df) <- c("Cramer's V", "p-value")
rownames(cramers_results_df) <- apply(variable_combinations, 2, paste,
                                      collapse = " & ")
print(cramers_results_df)
```

```{r eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
## Application of the Naïve Bayes
set.seed(123)
trainRowNumber <- createDataPartition(data$target, p = 0.7, list = FALSE)
train_data <- data[trainRowNumber, ]
test_data <- data[-trainRowNumber, ]

model <- naiveBayes(target ~ ., data = train_data)

predictions <- predict(model, test_data)

pred_prob <- prop.table(table(predictions))

confusionMatrix(table(predictions, test_data$target), positive = "1")

predicted_probabilities <- predict(model, newdata = test_data, type = "raw")

probabilities_switch_job <- predicted_probabilities[, 2]

test_data_with_probs <- cbind(test_data, probabilities_switch_job)
```

**Appendix A**

```{r eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE, fig.height=10, fig.width=8}
get_color <- function(median_prob) {
  if (median_prob > 0.72) {
    return("green")
  } else if (median_prob > 0.33) {
    return("yellow")
  } else {
    return("red")
  }
}

median_probs_experience <- test_data_with_probs %>%
  group_by(experience) %>%
  summarize(median_prob = median(probabilities_switch_job)) %>%
  mutate(color_experience = sapply(median_prob, get_color))

median_probs_company_type <- test_data_with_probs %>%
  group_by(company_type) %>%
  summarize(median_prob = median(probabilities_switch_job)) %>%
  mutate(color_company_type = sapply(median_prob, get_color))

median_probs_last_new_job <- test_data_with_probs %>%
  group_by(last_new_job) %>%
  summarize(median_prob = median(probabilities_switch_job)) %>%
  mutate(color_last_new_job = sapply(median_prob, get_color))

test_data_with_probs <- test_data_with_probs %>%
  left_join(median_probs_experience, by = "experience") %>%
  left_join(median_probs_company_type, by = "company_type") %>%
  left_join(median_probs_last_new_job, by = "last_new_job")

test_data_with_probs <- test_data_with_probs %>%
  mutate(color_experience = as.character(color_experience))

# experience vs predicted probabilities
plot1 <- ggplot(test_data_with_probs, aes(x = experience, 
                                          y = probabilities_switch_job, 
                                          fill = color_experience)) + 
  geom_boxplot() + 
  labs(title = "Relationship between Experience and Prob of Switching Jobs")+
  scale_fill_identity()


# company_type and predicted probabilities
plot2 <- ggplot(test_data_with_probs, aes(x = company_type, 
                                          y = probabilities_switch_job, 
                                          fill = color_company_type)) +
  geom_boxplot() +
  labs(title = "Relationship between Company Type and Prob of Switching Jobs")+
  scale_fill_identity()

# last_new_job vs predicted probabilities
plot3 <- ggplot(test_data_with_probs, aes(x = last_new_job, 
                                          y = probabilities_switch_job, 
                                          fill = color_last_new_job)) +
  geom_boxplot() +
  labs(title = "Relationship between Last-New Job and Prob of Switching Jobs")+
  scale_fill_identity()

combined_plot <- plot1 / plot2 / plot3 & theme(legend.position = "none")
combined_plot
```

\newpage


**Appendix B**

```{r eval = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Library check
library(ltm)
library(vcd)
library(dplyr)
library(ggplot2)
library(corrplot)
library(caretEnsemble)
library(ggcorrplot)
library(tidyverse)
library(e1071)
library(cluster)
library(mclust)
library(caret)
library(naivebayes)
library(patchwork)
library(pROC)
```

```{r eval = TRUE, echo = TRUE, message = FALSE, warning = FALSE, results = 'hide'}
# Data pre-processing 
load("JobChanges.RData")
dim(data)
head(data)
str(data)
summary(data)
```

```{r eval = TRUE, echo = TRUE, message = FALSE, warning = FALSE, results = 'hide'}
## Data manipulation
categorize_experience <- function(experience) {
  if (experience <= 2) {
    return("Junior")
  } else if (experience <= 5) {
    return("Mid-level")
  } else if (experience <= 10) {
    return("Senior")
  } else if (experience <= 20) {
    return("Manager")
  } else {
    return("Executive")
  }
}
data$experience <- factor(sapply(data$experience, categorize_experience), 
                                   levels = c("Junior", "Mid-level", "Senior",
                                              "Manager", "Executive"))

rebin_company_size <- function(size) {
  if (size %in% c("<10", "10-49")) {
    return("0-49")
  } else if (size %in% c("50-99")) {
    return("50-99")
  } else if (size %in% c("100-500")) {
    return("100-500")
  } else if (size %in% c("500-999", "1000-4999")) {
    return("500-9999")
  } else {
    return("10000+")
  }
}
data$company_size <- factor(sapply(data$company_size, rebin_company_size),
                            levels = c("0-49", "50-99", "100-500", 
                                       "500-9999", "10000+"))

# Checking the distribution for each categorical variable
contingency_table_gender <- table(data$gender)
contingency_table_relevant_experience <- table(data$relevant_experience)
contingency_table_education_level <- table(data$education_level)
contingency_table_major_discipline <- table(data$major_discipline)
contingency_table_company_type <- table(data$company_type)

# Cramér's V & Chi-Squared Test
cramers_v <- function(x, y) {
  table <- table(x, y)
  chi_sq <- chisq.test(table)
  n <- sum(table)
  phi_sq <- chi_sq$statistic / n
  r <- nrow(table) - 1
  k <- ncol(table) - 1
  min <- min(r, k)
  v <- sqrt(phi_sq / (min * (n - 1)))
  p_value <- chi_sq$p.value
  return(c("Cramer's V" = v, "p-value" = p_value))
}
variable_combinations <- combn(names(data)[sapply(data, is.factor)], 2)

cramers_results <- apply(variable_combinations, 2, function(vars) {
  cat_vars <- lapply(vars, function(var_name) data[[var_name]])
  cramer_v_and_p_value <- do.call(cramers_v, cat_vars)
  return(cramer_v_and_p_value)
})
cramers_results_df <- as.data.frame(t(cramers_results))
colnames(cramers_results_df) <- c("Cramer's V", "p-value")
rownames(cramers_results_df) <- apply(variable_combinations, 2, paste,
                                      collapse = " & ")
print(cramers_results_df)
```

```{r eval = TRUE, echo = TRUE, message = FALSE, warning = FALSE, results = 'hide'}
## Application of the Naïve Bayes
set.seed(123)
trainRowNumber <- createDataPartition(data$target, p = 0.7, list = FALSE)
train_data <- data[trainRowNumber, ]
test_data <- data[-trainRowNumber, ]

model <- naiveBayes(target ~ ., data = train_data)

predictions <- predict(model, test_data)

pred_prob <- prop.table(table(predictions))

confusionMatrix(table(predictions, test_data$target), positive = "1")

predicted_probabilities <- predict(model, newdata = test_data, type = "raw")

probabilities_switch_job <- predicted_probabilities[, 2]

test_data_with_probs <- cbind(test_data, probabilities_switch_job)
```

```{r eval = FALSE, echo = TRUE, message = FALSE, warning = FALSE, fig.height=10, fig.width=8, results = 'hide'}
#Plots
get_color <- function(median_prob) {
  if (median_prob > 0.72) {
    return("green")
  } else if (median_prob > 0.33) {
    return("yellow")
  } else {
    return("red")
  }
}

median_probs_experience <- test_data_with_probs %>%
  group_by(experience) %>%
  summarize(median_prob = median(probabilities_switch_job)) %>%
  mutate(color_experience = sapply(median_prob, get_color))

median_probs_company_type <- test_data_with_probs %>%
  group_by(company_type) %>%
  summarize(median_prob = median(probabilities_switch_job)) %>%
  mutate(color_company_type = sapply(median_prob, get_color))

median_probs_last_new_job <- test_data_with_probs %>%
  group_by(last_new_job) %>%
  summarize(median_prob = median(probabilities_switch_job)) %>%
  mutate(color_last_new_job = sapply(median_prob, get_color))

test_data_with_probs <- test_data_with_probs %>%
  left_join(median_probs_experience, by = "experience") %>%
  left_join(median_probs_company_type, by = "company_type") %>%
  left_join(median_probs_last_new_job, by = "last_new_job")

test_data_with_probs <- test_data_with_probs %>%
  mutate(color_experience = as.character(color_experience))

plot1 <- ggplot(test_data_with_probs, aes(x = experience, 
                                          y = probabilities_switch_job, 
                                          fill = color_experience)) + 
  geom_boxplot() + 
  labs(title = "Relationship between Company Type and Prob of Switching Jobs")+
  scale_fill_identity()

plot2 <- ggplot(test_data_with_probs, aes(x = company_type, 
                                          y = probabilities_switch_job, 
                                          fill = color_company_type)) +
  geom_boxplot() +
  labs(title = "Relationship between Company Type and Prob of Switching Jobs")+
  scale_fill_identity()

plot3 <- ggplot(test_data_with_probs, aes(x = last_new_job, 
                                          y = probabilities_switch_job, 
                                          fill = color_last_new_job)) +
  geom_boxplot() +
  labs(title = "Relationship between Last-New Job and Prob of Switching Jobs")+
  scale_fill_identity()

combined_plot <- plot1 / plot2 / plot3 & theme(legend.position = "none")

# ROC Curve
roc_curve <- roc(test_data$target, predicted_probabilities[, 2])
plot(roc_curve, main = "Figure 1. ROC Curve", col = "midnightblue", lwd = 2)
text(0.7, 0.3, paste("AUC =", round(roc_curve$auc, 3)), cex = 1)
```

\newpage

